spring:
  application:
    name : Server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/study_app
    username: postgres
    password: toor
  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true