spring:
  application:
    name : Server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/study_app
    username: postgres
    password: toor
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 2000MB

  web:


images_path: D:\data\images
