version: '3.9'

services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
      POSTGRES_DB: keycloakdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: bitnami/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_DATABASE_HOST: postgresql
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloakpassword
      KEYCLOAK_DATABASE_NAME: keycloakdb
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/keycloak.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/keycloak.key
      KC_HOSTNAME: 192.168.162.21
      KEYCLOAK_FRONTEND_URL: "https://192.168.162.21:8443"
    volumes:
      - ./certs:/etc/x509/https
    ports:
      - "8443:8443"
    depends_on:
      - postgresql
    networks:
      - keycloak-network
    command:
      - kc.sh
      - start
      - --https-port=8443
      - --http-enabled=false

volumes:
  postgres_data:

networks:
  keycloak-network:
    driver: bridge
